// Chat persistence routes — the app's conversation history.
//
//   GET    /api/chats          -> { chats: [{ id, title, created_at, updated_at }] }
//   GET    /api/chats/:id      -> full chat including messages
//   PUT    /api/chats/:id      -> upsert the whole chat (id generated by the app)
//   DELETE /api/chats/:id      -> remove a chat
//
// PUT is a full-state upsert on purpose: the app saves the entire message
// list after each turn, which makes saving idempotent — there's no
// create/append distinction to get out of sync.

import { Router } from 'express';
import { asyncHandler } from '../middleware/asyncHandler.js';
import { HttpError } from '../utils/httpError.js';
import { listChats, getChat, upsertChat, deleteChat } from '../lib/chats.js';

export const chatsRouter = Router();

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const MAX_MESSAGES = 300;

function readId(req) {
  const { id } = req.params;
  if (!UUID_RE.test(id)) {
    throw new HttpError(400, 'invalid_chat_id', 'Chat id must be a UUID.');
  }
  return id.toLowerCase();
}

chatsRouter.get(
  '/chats',
  asyncHandler(async (req, res) => {
    const limit = Math.min(Math.max(Number.parseInt(req.query.limit, 10) || 50, 1), 200);
    res.json({ chats: await listChats(limit) });
  }),
);

chatsRouter.get(
  '/chats/:id',
  asyncHandler(async (req, res) => {
    const chat = await getChat(readId(req));
    if (!chat) throw new HttpError(404, 'chat_not_found', 'No chat with that id.');
    res.json(chat);
  }),
);

chatsRouter.put(
  '/chats/:id',
  asyncHandler(async (req, res) => {
    const id = readId(req);
    const { title, messages } = req.body ?? {};

    if (!Array.isArray(messages) || messages.length === 0) {
      throw new HttpError(400, 'invalid_messages', 'Body must include a non-empty "messages" array.');
    }
    if (messages.length > MAX_MESSAGES) {
      throw new HttpError(400, 'chat_too_long', `A chat can hold at most ${MAX_MESSAGES} messages.`);
    }
    // Light shape check — every message must at least be a typed object.
    // The content is app-defined; the backend just stores and returns it.
    if (!messages.every((m) => m && typeof m === 'object' && typeof m.kind === 'string')) {
      throw new HttpError(400, 'invalid_messages', 'Every message needs a string "kind".');
    }

    await upsertChat({
      id,
      title: typeof title === 'string' && title.trim() ? title.trim().slice(0, 120) : 'Untitled chat',
      messages,
    });
    res.json({ saved: true });
  }),
);

chatsRouter.delete(
  '/chats/:id',
  asyncHandler(async (req, res) => {
    await deleteChat(readId(req));
    res.json({ deleted: true });
  }),
);
